general:
  allow-bStats: true
  disable-safe-warning-message: false
bot:
  disable-network-logs: false
  disable-bot-logs: false
  new-logger:
    bot-logs: true
    network-logs: true
  contact-cache:
    enable-friend-list-cache: false
    enable-group-member-list-cache: false
    save-interval-millis: 60000
